Update TEST-RELEASE-14-01.yml

diff --git a/.github/workflows/TEST-RELEASE-14-01.yml b/.github/workflows/TEST-RELEASE-14-01.yml
--- a/.github/workflows/TEST-RELEASE-14-01.yml
+++ b/.github/workflows/TEST-RELEASE-14-01.yml
@@ -16,11 +16,16 @@ jobs:
       - name: Disable workflow
         if: always()
         run: |
-          curl \
+          response=$(curl -s -o /dev/null -w "%{http_code}" \
             -X PUT \
             -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/disable
+            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/disable)
+          echo "Response: $response"
+          if [[ $response -ne 204 ]]; then
+            echo "Failed to disable workflow"
+            exit 1
+          fi
 
   DOCKERHUB:
     needs: [build]
